Eaton_DG_PCC/Models/Device_List.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_List
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ImageUrl { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public string Telephone { get; set; }
    }
}

Eaton_DG_PCC/Models/Test.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID { get; set; }
        public string DeviceId { get; set; }
        public string Ts { get; set; }
        public string Test1 { get; set; }
        public string Test2 { get; set; }
        public string Test3 { get; set; }
        public string Test4 { get; set; }
        public string Test5 { get; set; }
        public string Test6 { get; set; }
        public string Test7 { get; set; }
        public string Test8 { get; set; }
        public string Test9 { get; set; }
        public string Test10 { get; set; }
        public string Test11 { get; set; }
        public string Test12 { get; set; }
        public string Test13 { get; set; }
        public string Test14 { get; set; }
        public string Test15 { get; set; }
        public string Test16 { get; set; }
        public string Test17 { get; set; }
        public string Test18 { get; set; }
        public string Test19 { get; set; }
        public string Test20 { get; set; }
        public string Test21 { get; set; }
        public string Test22 { get; set; }
        public string Test23 { get; set; }
        public string Test24 { get; set; }
        public string Test25 { get; set; }
        public string Test26 { get; set; }
        public string Test27 { get; set; }
        public string Test28 { get; set; }
        public string Test29 { get; set; }
        public string Test30 { get; set; }
        public string Test31 { get; set; }
        public string Test32 { get; set; }
        public string Test33 { get; set; }
        public string Test34 { get; set; }
        public string Test35 { get; set; }
        public string Test36 { get; set; }
        public string Test37 { get; set; }
        public string Test38 { get; set; }
        public string Test39 { get; set; }
        public string Test40 { get; set; }
        public string Test41 { get; set; }
        public string Test42 { get; set; }
        public string Test43 { get; set; }
        public string Test44 { get; set; }
        public string Test45 { get; set; }
        public string Test46 { get; set; }
        public string Test47 { get; set; }
        public string Test48 { get; set; }
        public string Test49 { get; set; }
        public string Test50 { get; set; }
        public string Test51 { get; set; }
        public string Test52 { get; set; }
        public string Test53 { get; set; }
        public string Test54 { get; set; }
        public string Test55 { get; set; }
        public string Test56 { get; set; }
        public string Test57 { get; set; }
        public string Test58 { get; set; }
        public string Test59 { get; set; }
        public string Test60 { get; set; }
        public string Test61 { get; set; }
        public string Test62 { get; set; }
        public string Test63 { get; set; }
        public string Test64 { get; set; }
        public string Test65 { get; set; }
        public string Test66 { get; set; }
        public string Test67 { get; set; }
        public string Test68 { get; set; }
        public string Test69 { get; set; }
        public string Test70 { get; set; }
        public string Test71 { get; set; }
        public string Test72 { get; set; }
        public string Test73 { get; set; }
        public string Test74 { get; set; }
        public string Test75 { get; set; }
        public string Test76 { get; set; }
        public string Test77 { get; set; }
        public string Test78 { get; set; }
        public string Test79 { get; set; }
        public string Test80 { get; set; }
        public string Test81 { get; set; }
        public string Test82 { get; set; }
        public string Test83 { get; set; }
        public string Test84 { get; set; }
        public string Test85 { get; set; }
        public string Test86 { get; set; }
        public string Test87 { get; set; }
        public string Test88 { get; set; }
        public string Test89 { get; set; }
        public string Test90 { get; set; }
        public string Test91 { get; set; }
        public string Test92 { get; set; }
        public string Test93 { get; set; }
        public string Test94 { get; set; }
        public string Test95 { get; set; }
        public string Test96 { get; set; }
        public string Test97 { get; set; }
        public string Test98 { get; set; }
        public string Test99 { get; set; }
        public string Test100 { get; set; }
    }
}

Eaton_DG_PCC/Controllers/PCTronController.cs
using LinqToExcel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Eaton_DG_PCC.BigScreen;
using Eaton_DG_PCC.Model;
using Eaton_DG_PCC.Model.DRAQ127;
using Eaton_DG_PCC.Models;
using Eaton_DG_PCC.Model.PCC;

namespace Eaton_DG_PCC.Controllers
{
    public class PCTronController : Controller
    {

        // GET: PCTron-需要修改服务器地址

        private PCTronEntities db2 = new PCTronEntities();
        //private SYRSCMEntities db = new SYRSCMEntities();
        private Device_List devicelist = new Models.Device_List();
        Dbs dbs = new Model.Dbs();
        DB_Single_station db_Single_station = new DB_Single_station();
        DB_Overall_Situation db_Overall_Situation = new DB_Overall_Situation();
        string dtStart, dtEnd;
        ArrayList arraylist = new ArrayList();

        //PHP-ServerPC-需要修改服务器地址1
        //string SqlCon1 = @"Data Source=test-PC\AndyLi;";
        //public static string SqlCon_PCTron = @"Data Source=test-PC\AndyLi;Initial Catalog=PCTron;User ID=sa;Password=ok;";
        //public static string SqlCon_DRAQ75 = @"Data Source=test-PC\AndyLi;Initial Catalog=DRAQ75;User ID=sa;Password=ok;";

        DB_DRAQ127 db_draq127 = new DB_DRAQ127();

        string Now_Years = DateTime.Now.Year.ToString();
        string Now_Months = DateTime.Now.Month.ToString();
        string Last_Months = DateTime.Now.AddMonths(-1).Month.ToString();


        string years = System.DateTime.Now.Year.ToString();
        string months = System.DateTime.Now.Month.ToString();
        string days = System.DateTime.Now.Day.ToString();

        string hours = System.DateTime.Now.Hour.ToString();
        string minutes = System.DateTime.Now.Minute.ToString();
        string seconds = System.DateTime.Now.Second.ToString();


        public ActionResult Login()
        {

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]//该注解可以防止跨站攻击
        [ActionName("Login")]//该注解可以更改路由中Action名称
        public ActionResult Login(User model)
        {


            //if (!ModelState.IsValid)
            //{
            //    //用户输入服务端验证,此处处理验证不通过的提示代码 本例略过             
            //    return View("Login");
            //}
            string result = null;
            string sql = "select* from Users where UserName = '" + model.UserName + "' and PassWord = '" + model.Password + "'";
            User user = dbs.Select_UserInfo(sql); //执行Reader查询，存入dr
            if (user.RoleNum != null & user.RoleNum != "")
            {
                if (user.RoleNum == "1")
                {
                    result = "Admin,Edit,Select";
                }
                else if (user.RoleNum == "2")
                {
                    result = "Edit,Select";
                }
                else if (user.RoleNum == "3")
                {
                    result = "Select";
                }
            }




 
           if (result == null)
           {
                //ViewData["msg"] = "登陆失败";
                //用户名或者密码不正确的提示代码 本例略过

                return Content("<script>alert('UserName or Password Error !');history.go(-1);</script>");
            }
           else
           {
                //if () { } else { 
               //用户登陆核心代码
               FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(
                    1,
                    model.UserName,
                    DateTime.Now,
                    DateTime.Now.AddHours(12),//记住密码的时间
                    model.RememberMe,//是否保存cookie 记住密码
                    result //获取的用户权限列表 用逗号分割的字符串
                    );
               string encryptedTickt = FormsAuthentication.Encrypt(authTicket);
               HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTickt);
               Response.Cookies.Add(authCookie);
 
               Response.Redirect("/PCTron/", true);
               ActionResult empty = new EmptyResult();

                //return empty;
                return RedirectToAction("Indexs");
                
            }
        }

        public ActionResult Register()
        {

            return View();

        }


        public ActionResult Role_Manage()
        {

            String str = "proc_Select_UserInfoAll";
            List<User> list = dbs.Select_UserInfoAll(str);
            for (int i = 0; i < list.Count; i++)
            {
                ViewBag.ID = list[i].ID;
            }
            return View(list);

        }



        public ActionResult Add_Users()
        {
            int ID = Convert.ToInt32(Request["ID"]) + 1;
            ViewBag.ID = ID;



            List<Role_Info> role_info = new List<Role_Info>();
            List<Depart_Info> depart_info = new List<Depart_Info>();

            String Role_Info = "select * from Role_Manage";
            String Depart_Info = "select * from DepartInfo";
            role_info = dbs.Select_RoleInfoAll(Role_Info);
            depart_info = dbs.Select_DepartInfoAll(Depart_Info);


            return View(Tuple.Create(role_info, depart_info));


        }


        [HttpPost]
        public string Add_Users(List<User> model)
        {
            List<User> user=model;

            string username = "";
            string password = "";
            string rolenum = "";
            string realname = "";
            string email = "";
            string phone = "";
            string department="";
            foreach (var item in user)
            {
               username =  item.UserName;
               password = item.Password;
               rolenum = item.RoleNum;
               realname = item.RealName;
               email = item.Email;
               phone = item.Phone;
               department = item.DepartNum;
            }
            String sql = " insert into Users(UserName,PassWord,RoleNum,RealName,Email,Phone,DepartNum) values( '" + username + "','" + password + "','" + rolenum + "','" + realname + "','" + email + "','" + email + "','" + department + "')";
            int result = Dbs.ExecuteNonQuery(sql);
            if (result == 1) {
                return "Success";
            } else {
                return "no";
            }


        }


        public ActionResult Edit_Role(int? ID)
        {

            string DeviceId = Request["DeviceId"];



            String str = "exec proc_Select_Basic_Manage   '" + ID + "'";
            List<Role_Info> role_info = new List<Role_Info>();
            List<Depart_Info> depart_info = new List<Depart_Info>();

            String Role_Info = "select * from Role_Manage";
            String Depart_Info = "select * from DepartInfo";
            role_info = dbs.Select_RoleInfoAll(Role_Info);
            depart_info = dbs.Select_DepartInfoAll(Depart_Info);


            User list = dbs.Select_Role_Info(str);
            return View(Tuple.Create(list, role_info, depart_info));
        }

        [HttpPost]
        public ActionResult Edit_Role(List<String> Role_manage)
        {
            string ID = Role_manage[0];
            //string UserName = Role_manage[1];
            string Password = Role_manage[1];
            string Role = Role_manage[2];
            string RealName = Role_manage[3];
            string Phone = Role_manage[4];
            string DepartNum = Role_manage[5];


            //string newUserName = Leach(UserName);
            string newPassword = Leach(Password);
            string newRole = Leach(Role);
            string newRealName = Leach(RealName);
            string newPhone = Leach(Phone);
            string newDepartNum = Leach(DepartNum);

            String sql = "exec proc_Update_Role_Manage '" + ID + "','" + newPassword + "','" + newRole + "','" + newRealName + "','" + newPhone + "','" + newDepartNum + "'";
            int result = Dbs.ExecuteNonQuery(sql);
            if (result == 1)
            {
                ViewBag.saveStatus = 1;
                // return 1;
                String tip = "Success";
                return JavaScript(tip);
            }
            else
            {
                ViewBag.saveStatus = 0;
                String tip = "Fail";
                return JavaScript(tip);
                //return Content("<script>alert('no');history.go(-1);</script>");
            }

        }


        [HttpPost]
        public String Delete_Role(int id)
        {
            String sql = "proc_Delete_Role '" + id + "'";
            int result = Dbs.ExecuteNonQuery(sql);
            if (result == 1)
            {
                ViewBag.saveStatus = 1;
                // return 1;
                String tip = "success";
                //return RedirectToAction("Basci_faq");
                return tip;
            }
            else
            {
                ViewBag.saveStatus = 0;
                String tip = "Fail";
                return tip;
                //return Content("<script>alert('no');history.go(-1);</script>");
            }
        }



        public ActionResult DRAQ127()
        {
            string DeviceId = Request["DeviceId"];
            ViewBag.DeviceId = DeviceId;
            //String str = "exec proc_Device_Info '" + DeviceId + "'";
            //AllStatus list = dbs.DeviceAllStatus_DRAQ127(str);
            //ViewBag.Display_Model = list.Now_Model.ToString();

            String str_Monthly_Output_list = "proc_Select_Monthly_Output_PCTron";
            List<Monthly_Output_PCTron> Monthly_Output_list = dbs.Select_Monthly_Data_Output(str_Monthly_Output_list);
            //ViewBag.Monthly_Output_list = Monthly_Output_list;
            String str_Monthly_NG_list = "proc_Select_Monthly_NG_PCTron";
            List<Monthly_NG_PCTron> Monthly_NG_list = dbs.Select_Monthly_Data_NG(str_Monthly_NG_list);
            ViewBag.Monthly_OK_list = Monthly_NG_list;

Eaton_DG_PCC/Views/PCTron/Basic_faq.cshtml
@model IEnumerable<Eaton_DG_PCC.Model.Basic_Faq>

@{
    Layout = null;
    string ids = "-1";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Remote data acquisition system</title>
    <meta name="keywords" content="远程通讯系统keywords">
    <meta name="description" content="远程通讯系统description">
    <link href="~/Css/bootstrap.min14ed.css" rel="stylesheet" />
    <link href="~/Css/animate.min.css" rel="stylesheet" />
    <link href="~/Css/style.min862f.css" rel="stylesheet" />
    <link href="~/Css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="~/Css/plugins/sweetalert/sweetalert.css" rel="stylesheet">


</head>

<body class="gray-bg">
    


    <div class="row">
        <div class="col-sm-12">
            <div class="wrapper wrapper-content animated fadeInUp">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="ibox">
                            <div class="ibox-title">
                                <h5>All FAQ</h5>
                                <div class="ibox-tools">
                                    <a href="@Url.Action("Add_Faq","PCTron", new {DeviceId =@ViewBag.DeviceId})" class="btn btn-primary btn-xs ">Add FAQ</a>
                                </div>
                            </div>


                            @*<div class="ibox-content">
                                <div class="row m-b-sm m-t-sm">
                                    <div class="col-md-1">
                                        <button type="button" id="loading-example-btn" class="btn btn-white btn-sm"><i class="fa fa-refresh"></i> Refresh</button>
                                    </div>
                                    <div class="col-md-11">
                                        <div class="input-group">
                                            <input type="text" placeholder="Please enter the query content" class="input-sm form-control"> <span class="input-group-btn">
                                                <button type="button" class="btn btn-sm btn-primary">Search</button>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                            </div>*@



                        </div>
                    </div>
                </div>

@foreach (Eaton_DG_PCC.Model.Basic_Faq item in Model)
{
                <div class="faq-item">
                    <div class="row">
                        <div class="col-md-7">
                            <a data-toggle="collapse" href="faq.html#@item.ID" class="faq-question">@item.Problem</a>
                            <small><strong>Model：@item.DeviceId    </strong><br /> <i class="fa fa-clock-o"></i>Edit time： @item.Ts</small>
                        </div>
                        @*<div class="col-md-2">
                            <span class="small font-bold">dong guan branch</span>
                            <div class="tag-list">
                                <span class="tag-item">2# Automatic production line</span>
                            </div>
                        </div>*@
                        <div class="col-md-3 text-left">
                            <span class="small font-bold">Owner</span>
                            <br />@item.Owner
                        </div>
                        <div class="col-md-2">
                            <a href="@Url.Action("Edit_Faq","PCTron", new { ID=@item.ID ,DeviceId =@item.DeviceId })" class="btn btn-white btn-sm">
                                <i class="fa fa-pencil"></i> Edit </a>
                            
                            
                                <a  onclick="Delete(@item.ID)" class="btn btn-white btn-sm ">
                                @*<a href="@Url.Action("Delete_Faq","PCTron", new { ID=@item.ID})" class="btn btn-white btn-sm">*@
                                <i class="fa fa-trash-o "></i> Delete
                            </a>
</div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div id="@item.ID" class="panel-collapse collapse faq-answer">
                                <p>
                                    @item.Answer
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                    </div>
}
            </div>
        </div>
    </div>
    <script src="~/scripts/jquery.min.js?v=2.1.4"></script>
    <script src="~/scripts/bootstrap.min.js?v=3.3.6"></script>
    <script src="~/scripts/plugins/sweetalert/sweetalert.min.js"></script>
    @*<script>
        $(document).ready(function(){$("#loading-example-btn").click(function(){btn=$(this);simpleLoad(btn,true);simpleLoad(btn,false)})});function simpleLoad(btn,state){if(state){btn.children().addClass("fa-spin");btn.contents().last().replaceWith(" Loading")}else{setTimeout(function(){btn.children().removeClass("fa-spin");btn.contents().last().replaceWith(" Refresh")},2000)}};
    </script>*@

    <script>
        //删除信息
       
        
        function Delete(categoryID) {
            swal({
                title: "Sure you want to delete it?", text: "Delete post will not be able recovery,please exercise caution！", type: "warning", showCancelButton: true, confirmButtonColor: "#DD6B55", confirmButtonText: "Yes，I want delete！", cancelButtonText: "I then consider…", closeOnConfirm: false, closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    //swal("删除成功！", "您已经永久删除了这条信息。", "success")

                    url = "/PCTron/Delete_Faq";
                    parameter = { id: categoryID };
                    $.post(url, parameter, function (data) {
                        if (data == "success") {
                            swal("Delete successfully！", "You permanently delete the information。", "success")
                            //history.go(-1); 
                            //alert("删除成功！");
                            //window.location = "/PCTron";
                            setTimeout(function(){
                                window.location.href = window.location.href;
                            },3000)
                            
                        }else{alert("Delete failure！");}
                    });
                } else {
                    swal("Cancel", "You cancel the operation！", "error")
                }
            })
        }
        
    </script>
</body>


</html>

Eaton_DG_PCC/Views/PCTron/Indexs.cshtml
@model IEnumerable<Eaton_DG_PCC.Models.AllStatus>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    
    <meta name="viewport" content="width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" /> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title>Remote data acquisition system</title>
    <meta name="keywords" content="远程通讯系统keywords">
    <meta name="description" content="远程通讯系统description">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico">
    <link href="~/Css/bootstrap.min14ed.css" rel="stylesheet" />
    <link href="~/Css/font-awesome.min93e3.css" rel="stylesheet" />
    <link href="~/Css/animate.min.css" rel="stylesheet" />
    <link href="~/Css/style.min862f.css" rel="stylesheet" />

</head>


<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close">
                <i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span><img alt="image" 
                                       src="~/img/Eaton.gif"/></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="">
                                <span class="clear">
                                    <span class="block m-t-xs"><strong class="font-bold">@ViewData["name"].ToString()</strong></span>
                                    @if (@ViewData["role"].ToString() == "Admin,Edit,Select") {
                                    <span class="text-muted text-xs block">Super Admin<b class="caret"></b></span>
                                    }else if (@ViewData["role"].ToString() == "Edit,Select") {
                                    <span class="text-muted text-xs block">Admin<b class="caret"></b></span>
                                    }
                                    else if (@ViewData["role"].ToString() == "Select") {
                                    <span class="text-muted text-xs block">Guest<b class="caret"></b></span>
                                    }
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">

                               
                                <li>
                                    <a href="@Url.Action("LogOff", "PCTron", new { username =@ViewData["name"].ToString() })">Exit</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            AME+
                        </div>
                    </li>

                        
                    <li>
                        <a class="J_menuItem" href="@Url.Action("Device_List", "PCTron")">
                            <i class="fa fa-home"></i>
                            <span  >Device Info</span>
                            <span class="fa arrow"></span>
                        </a>
                      
                    </li>


                    @*<li>
                        <a class="J_menuItem" href="@Url.Action("Maintenance_info", "PCTron")">
                            <i class="fa fa fa-thumbs-up"></i>
                            <span  >Maintenance info</span>
                            <span class="fa arrow"></span>
                        </a>
                       
                    </li>

                    <li>
                            <a class="J_menuItem" href="@Url.Action("Spare_Parts_List", "PCTron")"><i class="fa fa-university"></i> <span>Spare Parts</span><span class="fa arrow"></span></a>

                        </li>

                    <li>
                        <a class="J_menuItem" href="@Url.Action("FAQ", "PCTron")"><i class="fa fa-question-circle"></i> <span >FAQ</span><span class="fa arrow"></span></a>
                       
                    </li>

                    <li>
                        <a href="@Url.Action("BigScreen4", "PCTron")">
                            <i class="fa fa-bar-chart-o"></i> <span class="nav-label">Overall situation</span><span class="fa arrow"></span>
                        </a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-user"></i> <span class="nav-label">Privilege management</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Role_Manage", "PCTron")">Role management</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" href="@Url.Action("CI", "PCTron")"><i class="fa fa-question"></i> <span>CI</span><span class="fa arrow"></span></a>
                    </li>
                    <li class="J_tabCloseAll">
                        
                        <a>
                        <i class="fa fa-remove"></i><span class="nav-label">Close all tabs</span>
                        </a>
                    </li>*@

                    




                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
           

            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft">
                    <i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="index_v1.html">Index</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight">
                    <i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">
                        closing<span class="caret"></span>
                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive">
                            <a>Locate the current TAB</a>
                        </li>
                        <li class="J_tabCloseAll">
                            <a>Close all tabs</a>
                        </li>
                        <li class="J_tabCloseOther">
                            <a>Close the other tabs</a>
                        </li>
                    </ul>
                </div>
                <a href="@Url.Action("LogOff", "PCTron", new { username =@ViewData["name"].ToString() })" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> Exit</a>
            </div>
            <!--默认加载页面-->
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="/PCTron/Device_List" frameborder="0" data-id="index_v1.html" seamless></iframe>
            </div>
            

        </div>
        <!--右侧部分结束-->


    </div>






    <script src="~/scripts/jquery.min.js"></script>

    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/scripts/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/scripts/plugins/layer/layer.min.js"></script>
    <script src="~/scripts/hplus.min.js"></script>
    <script src="~/scripts/contabs.min.js"></script>
    <script src="~/scripts/plugins/pace/pace.min.js">
    </script>


    <script>
       !function(){
           var i = screen.width / 750;
           document.write('<meta name="viewport"content="width=750,initial-scale='+i+",maximum-scale="+i+", minimum-scale="+i+',user-scalable=no,target-densitydpi=device-dpi,minimal-ui"/>');
       }();
       //plus.screen.lockOrientation("landscape");//锁定横屏 左右旋转 默认不会还原
       



       //function select_NetworkStatus() {
       //    $.ajax({
       //        dataType: "json",
       //        type: "post",
       //        url: '/DRAQ127/DRAQ127_AllStatus_NetworkStatus',
       //        data: {},
       //        success: function (data) {
       //            if(data.msg==1){
       //                alert("ok");
       //            }
       //           // alert("ok");
       //        },
       //        error: function (data) {
       //            //alert("系统错误");
       //        }
       //    })
       //};

       //window.setInterval(function () {
       //    select_NetworkStatus();
       //}, 3000);

    </script>


</body>


</html>